version: "3.3"

volumes:
    prometheus_data: {}

services:
    joomla:
        image: erfanemoon/joomla_img
        hostname: joomla
        deploy:
            placement:
               constraints: 
                - node.role == worker
            labels:  
              - "traefik.enable=true"
              - "traefik.port=80"
              #- "traefik.backend=joomla"
              - "traefik.frontend.rule=Host:joomla.localhost"
              - "traefik.docker.network=app_traefik"  
        entrypoint: ["wait-for-it.sh", "-t", "120", "db:3306", "--", "docker-php-entrypoint", "-D FOREGROUND"] 
        depends_on:
            - db  
        volumes:
            - /gfs/joomla/:/var/www/html/
        networks:
            - traefik      
    pmy:
        image: phpmyadmin/phpmyadmin
        hostname: pmy
        depends_on: 
           - db
        deploy:
            placement:
               constraints: 
                - node.role == worker
            labels:
              - "traefik.enable=true"      
              - "traefik.port=80"
              - "traefik.backend=pmy"
              - "traefik.frontend.rule=Host:pmy.localhost"
              - "traefik.docker.network=app_traefik"  
        environment:
            DB_HOST: db
            MYSQL_ROOT_PASSWORD: qweasd
        volumes:
            - /gfs/phpmyadmin:/config
        networks:
            - traefik    
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        hostname: db
        ports:
           - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: qweasd
        volumes:
            - /gfs/mysql:/var/lib/mysql
        networks:
            - traefik    
    prometheus:
        image: prom/prometheus:latest
        depends_on: 
           - node-exporter
           - cadvisor
        volumes:
            - /home/erfan/joomla/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus  
              #- ./prometheus:/etc/prometheus
              #- prometheus_data:/prometheus 
              #- ./monitoring/prometheus/alert.rules:/etc/prometheus/alert.rules
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9090:9090
        deploy:
            placement:
              constraints:
                 - node.role == manager
            labels:
              - "traefik.enable=true"      
              - "traefik.port=9090"
              - "traefik.backend=prometheus"
              - "traefik.frontend.rule=Host:prometheus.localhost"
              - "traefik.docker.network=app_traefik"  
        networks:
            - traefik    
    node-exporter:
        image: prom/node-exporter:latest
        volumes:       
            - /proc:/host/proc:ro       
            - /sys:/host/sys:ro       
            - /:/rootfs:ro       
        command:       
            - '--path.procfs=/host/proc'       
            - '--path.sysfs=/host/sys'       
            - '--path.rootfs=/host'       
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'  
        ports:
            - '9100:9100'
        deploy:       
            mode: global 
        networks:
             - traefik    
              
    grafana:
        image: grafana/grafana:latest
        depends_on: 
            - prometheus
        volumes: 
            - /gfs/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
            - GF_SERVER_DOMAIN=localhost:3000
            - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        deploy:
            placement:
                constraints:
                   - node.role == manager
            labels:
              - "traefik.enable=true"
              - "traefik.port=3000"
              - "traefik.backend=grafana"
              - "traefik.frontend.rule=Host:grafana.localhost"
              - "traefik.docker.network=app_traefik"  
        networks:
           - traefik    
          #- intnet
          #- extnet  
    cadvisor:
        image: google/cadvisor:latest
        #privileged: true
        volumes:
            - /:/rootfs:ro 
            - /var/run:/var/run:rw
            - /sys:/sys:ro 
            - /var/lib/docker/:/var/lib/docker:ro 
            #- /dev/disk/:/dev/disk:ro #
        ports:
           - 8084:8080
        deploy:
            mode: global
        networks:
            - traefik
    proxy:
        image: traefik:1.4
        hostname: traefik_
        #command:
            #- '--api=true'
            #- '--api.debug=true'
            #- '--api.insecure=true'
            #- '--api.dashboard=true'  
            #- '--providers.docker=true'
            #- --traefik.http.routers.traefik.rule=Host(`traefik.localhsot`)  
            #- '--providers.docker=true'
            #- '--providers.docker.watch=true'  
            #- '--providers.docker.endpoint=unix:///var/run/docker.sock'
            #- '--providers.docker.swarmMode=true'
            #- '--providers.docker.exposedbydefault=false'
            #- '--providers.docker.network=app_intnet' 
            #- '--entrypoints.web.address=:80'
            #- '--providers.docker.constraints=Label(`traefik.tags`,`public`)'  
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            #- /home/erfan/joomla/config.toml:/etc/traefik/traefik.toml  
            #- /home/erfan/joomla/config.toml:/etc/traefik/traefik.toml  

            #- /home/erfan/joomla/data/traefik.yml:/traefik.yml:ro
            #- /home/erfan/joomla/data/acme.json:/acme.json  
        configs:
          - source: traefik-config
            target: /etc/traefik/traefik.toml
        deploy:
            placement:
                constraints:
                    - node.role == manager
            #labels:
              #- traefik.enable=true
              #- traefik.docker.network=traefik
        networks: 
           #- intnet
           #- extnet
           - traefik  
networks:
      traefik:
        #driver: overlay
        external: true
configs:
  traefik-config:
    file: /home/erfan/joomla/config.toml
    
      #intnet:
          #internal: true
          #driver: overlay
          #ipam:
             #driver: default
             #config:
                #- subnet: 192.168.200.0/24
      #extnet:
         #driver: overlay
         #external: true
         #ipam:
            #driver: default
            #config:
                 #- subnet: 192.168.100.0/24
